version: 1
upload:
  - source: canonical/prometheus-rock
    commit: 4521b60dec190d3254901de3d9d2147cf806dc2b
    directory: 2.46.0
    release:
      2.46.0-22.04:
        end-of-life: "2024-09-08T00:00:00Z"
        risks:
          - stable
