version: 1
upload:
  - source: canonical/prometheus-rock
    commit: ebe3742f58628c2be2c385b1c300d33a5d519e0b
    directory: 2.37.0
    release:
      2.37.0-22.04:
        end-of-life: "2024-09-19T00:00:00Z"
        risks:
          - stable
  - source: canonical/prometheus-rock
    commit: ebe3742f58628c2be2c385b1c300d33a5d519e0b
    directory: 2.45.0
    release:
      2.45.0-22.04:
        end-of-life: "2024-09-19T00:00:00Z"
        risks:
          - stable
      2.45-22.04:
        end-of-life: "2024-09-19T00:00:00Z"
        risks:
          - stable
