version: 1
upload:
  - source: canonical/alertmanager-rock
    commit: 65573b0cb638594ea523543cbcdc4b6739561855
    directory: 0.31.1
    release:
      0-24.04:
        end-of-life: '2026-05-15T00:00:00Z'
        risks:
          - stable
      0.31-24.04:
        end-of-life: '2026-05-15T00:00:00Z'
        risks:
          - stable
      0.31.1-24.04:
        end-of-life: '2026-02-11T00:00:00Z'
        risks:
          - stable
