version: 1
upload:
  - source: canonical/alertmanager-rock
    commit: 3b9f61693793bcccd5352665583a264e39f5b01f
    directory: 0.31.0
    release:
      0-24.04:
        end-of-life: '2026-05-06T00:00:00Z'
        risks:
          - stable
      0.31-24.04:
        end-of-life: '2026-05-06T00:00:00Z'
        risks:
          - stable
      0.31.0-24.04:
        end-of-life: '2026-02-03T00:00:00Z'
        risks:
          - stable
